* ACM UPM Telegram Bot

Proyecto de la asociacion [[https://acm.asoc.fi.upm.es][ACM]] de la ETSIINF (FI) de la UPM para crear un bot.


1. [[#cómo-funciona][¿Cómo funciona?]]
2. [[#cómo-hacerlo-funcionar][¿Cómo hacerlo funcionar?]]

#+NAME: como-funciona
** ¿Cómo funciona?

Lo primero que necesitarás es abrir una conversación con él, búscalo con el nombre @acmupm_bot

Lista de comandos:
- /start :: Comienza el bot
- /help :: Muestra los comandos disponibles
- /quehaceacm :: ¡Conoce más sobre ACM UPM!
- /precios :: Si quieres comer algo, necesitarás saber cuánto cuesta.
- /eventos :: Muestra los eventos actuales en ACM
- /lmgtfy :: Por si no sabes algo...
- /tldr :: TL;DR
- /reto :: ¿Quieres hacer algún reto de programación?

Lista de comandos para ADMINISTRADORES:
- /update :: Actualiza el bot descargando el último commit de este repositorio
- /newreto [URL de un reto] :: Cambia el reto por el que se indique en el campo _URL de un reto_

Estos comandos solo estarán disponibles para los usuarios de Telegram añadidos al archivo *admins.json* con el formato:

#+BEGIN_EXAMPLE
["123456789"]
#+END_EXAMPLE

Siendo *123456789* el identificador del administrador en Telegram

#+NAME: como-hacerlo-funcionar
** ¿Cómo hacerlo funcionar?

Solo unos pocos elegidos de momento pueden ponerlo en marcha. En un
futuro nadie más podrá, solo el administrador.  

Si eres uno de los afortunados, necesitarás tener el TOKEN que el
todopoderoso BotFather nos entregó ((por tercera vez)*)** guardado en un fichero llamado:

acm.token

Pon el token en el fichero "acm.token" en el mismo directorio que
el bot y ejecútalo mediante:

#+BEGIN_SRC bash
python bot.py 
#+END_SRC

El bot se encarga del resto.

*EDIT: cuarta vez
**EDIT: quinta vez
